---
title: "Comparing Covidestim Models"
author: "Quinn White"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    df_print: paged
    code_folding: show
    css: !expr here::here('css/template.css')
  html_document:
    df_print: paged
    toc-depth: 4
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../output_html")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Relevant sections of `covidestim/inst/stan/stan_program_default.stan` from before the adjustments for Omicron (the file [here](https://github.com/covidestim/covidestim/blob/6151c275fdfa085f750fb20d2e63a5e784c76b15/inst/stan/stan_program_default.stan)) and the most recent model version (the file [here](https://github.com/covidestim/covidestim/blob/master/inst/stan/stan_program_default.stan)).


# Handling reinfections differently 

## Previous Version

Subtracting infections from population size.

```{stan output.var="", eval=FALSE}

 pop_uninf = pop_size;
  for(i in 1:N_days_tot) {
    if(i==1){
      logRt[i] = logRt0[i];
    } else{
      logRt[i] = logRt0[i] + log(pop_uninf/pop_size);
    }
    deriv1_log_new_inf[i] = logRt[i]/serial_i;
    log_new_inf[i] = sum(deriv1_log_new_inf[1:i]) + log_new_inf_0;
    new_inf[i] = (1-exp(-exp(log_new_inf[i])/pop_uninf)) * pop_uninf;
    pop_uninf -= new_inf[i];
    if (pop_uninf < 1) {
      // print("WARNING pop_uninf preliminary value was ", pop_uninf);
      pop_uninf = 1;
    }
  }
  
```

## New Version

Incorporating reinfections

```{stan output.var="", eval=FALSE}

  // NEW INCIDENT CASES
  
  // modeled with a spline
  //     spl_par_rt[2:N_spl_par_rt] = spl_par_rt0; 
  // spl_par_rt[1] = (spl_basis_rt[2+N_days_before,2:N_spl_par_rt]-
  //                  spl_basis_rt[1+N_days_before,2:N_spl_par_rt]) * spl_par_rt0 / 
  //                 (spl_basis_rt[1+N_days_before,1]-spl_basis_rt[2+N_days_before,1]);
  logRt0 = spl_basis_rt * spl_par_rt;
  ever_inf = pop_size * cum_p_inf_init; // initial ever infected population
  population_protection_init[1] = pop_size * start_p_imm; // initial (waning) protection from vax/inf/boost
  if(N_weeks_before > 0){
    // if there are before weeks modeled, the initial effective protection
    // equals the population that will never be infected by the start date of the data
    // i.e., the date for which the cum_p_inf_init and start_p_imm are reported.
    effective_protection_prvl[1] = pop_size * (1 - cum_p_inf_init);
  } else {
    // if there are no before weeks modeled, the initial effecive protection is 
    // the complete immune population
    effective_protection_prvl[1] = pop_size * start_p_imm;
  }
  susceptible_prvl[1] = pop_size - effective_protection_prvl[1];
  // effective_protection_inf_prvl[1] = pop_size * cum_p_inf_init;  //
  // effective protection from infections; for the first timepoint include everyone
  // with a historic infection; 


  // for(i in 1:N_days_tot) {
  for(i in 1:N_weeks_tot) {
   if(i > 1){
       susceptible_prvl[i] = pop_size - effective_protection_prvl[i-1];
   }

    if (susceptible_prvl[i] < 1) {
      // print("WARNING num_uninf preliminary value was ", num_uninf);
      susceptible_prvl[i] = 1;
    }
    logRt[i] = logRt0[i] + log(susceptible_prvl[i]/pop_size);

    deriv1_log_infections[i] = logRt[i]/serial_i;

    log_infections[i] = sum(deriv1_log_infections[1:i]) + log_infections_0;

    infections[i] = exp(log_infections[i]);

    // prot_boost[i] = sum(obs_boost[1:i] * 0.8);
    // if(i > N_days_before){
    // wane_boost[i] = sum(obs_boost[1:i-N_days_before] .* (.35 * exp(-.008 * idx3[N_days_tot-(i-N_days_before)+1:N_days_tot]) + .45) );
    if(i > N_weeks_before){
      // for the observed data weeks, population protection is calculated for the 
      // waning of the initial immunity since the observed data started;
      // waning of booster immunity since the observed data started;
      // waning of the modeled infections since the observed data started 
      // (note that any infections prior to this date are implicitly included in the start_p_imm)
    // wane_boost[i] = sum(obs_boost[1:i-N_weeks_before] .* (.35 * exp(-.008 * idx3[N_weeks_tot-(i-N_weeks_before)+1:N_weeks_tot]*7) + .45) );
    population_protection_init[i] = pop_size * start_p_imm * exp(-.008 * idx3[N_weeks_tot-i+N_weeks_before+1]*7) ; // increasse from 75% susceptible to 90% susceptible (10% remains rpotected)
    population_protection_boost[i] = sum(obs_boost[1:i-N_weeks_before]*.8 .* (exp(-.008 * idx3[N_weeks_tot-i+N_weeks_before+1:N_weeks_tot]*7)) );
    population_protection_inf[i] = sum(infections[N_weeks_before +1:i] .* ( exp(-.008 * idx3[N_weeks_tot-i+N_weeks_before+1:N_weeks_tot] * 7)));
    } else {
      // for the before period, population protected is only the sum of the initial population protected (never infected prior to start date)
      // and those infected before the start of the data.
population_protection_init[i] = pop_size * (1 - cum_p_inf_init);
population_protection_boost[i] = 0;
population_protection_inf[i] = sum(infections[1:i] .* ( exp(-.008 * idx3[N_weeks_before-i+1:N_weeks_before] * 7)));
    }
```


# Fitting with Hospitalizations Instead of Deaths


## Previous Version (Deaths) 

Deaths in the Likelihood:


```{stan  output.var="", eval= FALSE}

///// LIKELIHOOD
// Before data
  if(pre_period_zero==1){
    if(N_days_before>0){
      tmp_sum_cas_pre = sum(occur_cas[1:N_days_before]);
      tmp_sum_die_pre = sum(occur_die[1:N_days_before]);

      if (tmp_sum_cas_pre <= 0) // Account for floating point error
        tmp_sum_cas_pre = 0.0000000001;
      if (tmp_sum_die_pre <= 0) // Account for floating point error
        tmp_sum_die_pre = 0.0000000001;

      target += neg_binomial_2_lpmf( 0 | tmp_sum_cas_pre, phi_cas);
      target += neg_binomial_2_lpmf( 0 | tmp_sum_die_pre, phi_die);
    }
  }
  
// Observed data
  if (cas_yes == 1) {
    tmp_obs_cas = obs_cas[1];
    tmp_occur_cas = occur_cas[1 + N_days_before];

    for(i in 1:N_days) {

      if (tmp_occur_cas <= 0) // Account for floating point error
        tmp_occur_cas = 0.000000001;
      //
      //don't add to target if no observations are present
      if(i > lastCaseDate) {
        break;
      }

      
      // Don't add to `target` unless we have `N_days_av` of data accumulated
      // in `tmp_occur_cas`
      if (i >= N_days_av)
        target += neg_binomial_2_lpmf(tmp_obs_cas | tmp_occur_cas, phi_cas)/
          N_days_av;

      if(i>nda0){
        tmp_obs_cas   -= obs_cas[i - nda0];
        tmp_occur_cas -= occur_cas[i + N_days_before - nda0];
      }
      if(i<N_days){
        tmp_obs_cas   += obs_cas[i + 1];
        tmp_occur_cas += occur_cas[i + N_days_before + 1];
      }
    }
  }

  if (die_yes == 1){

    tmp_obs_die = obs_die[1];
    tmp_occur_die = occur_die[1 + N_days_before];

    for(i in 1:N_days) {

      if (tmp_occur_die <= 0) // Account for floating point error
        tmp_occur_die = 0.000000001;

      //don't add to target if no observations are present
      if(i > lastDeathDate) {
        break;
      }

      // Don't add to `target` unless we have `N_days_av` of data accumulated
      // in `tmp_occur_die`
      if (i >= N_days_av)
        target += neg_binomial_2_lpmf(tmp_obs_die | tmp_occur_die, phi_die)/
          N_days_av;

      if(i>nda0){  
        tmp_obs_die   -= obs_die[i - nda0];
        tmp_occur_die -= occur_die[i + N_days_before - nda0];
      }
      if(i<N_days){
        tmp_obs_die   += obs_die[i + 1];
        tmp_occur_die += occur_die[i + N_days_before + 1];
      }
    }
  }
    }
    
```

## New Version (Hospitalizations)

Fitted hospitalizations are taken to be the number of severe diagnoses -- relevant lines:

```{stan  output.var="", eval=FALSE}
// DIAGNOSIS // 
  // rate ratio of diagnosis at asymptomatic vs symptomatic, symptomatic vs severe
  rr_diag_sym_vs_sev = inv_logit(spl_basis_dx * logit(spl_par_sym_dx));
  p_diag_if_sym = p_diag_if_sev * rr_diag_sym_vs_sev;
  diagnoses_severe = p_diag_if_sev * conv1d(severe - dx_sym_sev, sev_diag_delay_rv);
fitted_hospitalizations = diagnoses_severe;

```


Hospitalizations in the Likelihood:

```{stan  output.var="", eval=FALSE}

// LIKELIHOOD
  // Before data
  if(pre_period_zero==1){
    // if(N_days_before>0){
    if(N_weeks_before>0){
  
      // if (sum(fitted_cases[1:N_days_before]) < 0)
      //   reject("`sum(fitted_cases[1:N_days_before])` had a negative value");
      // 
      // if (sum(fitted_deaths[1:N_days_before]) < 0)
      //   reject("`sum(fitted_deaths[1:N_days_before])` had a negative value");
      if (sum(fitted_cases[1:N_weeks_before]) < 0)
        reject("`sum(fitted_cases[1:N_weeks_before])` had a negative value");

      if (sum(fitted_hospitalizations[1:N_weeks_before]) < 0)
        reject("`sum(fitted_hospitalizations[1:N_weeks_before])` had a negative value");

      // target += neg_binomial_2_lpmf( 0 | sum(fitted_cases[1:N_days_before]), phi_cas);
      // target += neg_binomial_2_lpmf( 0 | sum(fitted_deaths[1:N_days_before]), phi_die);
      target += neg_binomial_2_lpmf( 0 | sum(fitted_cases[1:N_weeks_before]), phi_cas);
      target += neg_binomial_2_lpmf( 0 | sum(fitted_hospitalizations[1:N_weeks_before+4]), phi_hosp);
    }
  }

  if (min(fitted_cases) < 0)
    reject("`fitted_cases` had a negative value");

  if (min(fitted_hospitalizations) < 0)
    reject("`fitted_hospitalizations` had a negative value");

  // LIKELIHOOD
  // During data
  // target += neg_binomial_2_lpmf(
  //   // `obs_cas` from the first observed day to the last death date
  //   obs_cas_mvs[N_days_av:lastCaseDate] |
  //     // `fitted_cases` from the first observed day (`N_days_before+1`) to the
  //     // last death date
  //     fitted_cases_mvs[N_days_before+N_days_av : N_days_before+lastCaseDate],
  //   phi_cas
  // ) ;// Optional, but likely unncessesary: / N_days_av;
  // 
  // target += neg_binomial_2_lpmf(
  //   // `obs_die` from the first observed day to the last death date
  //   obs_die[N_days_av:lastDeathDate] |
  //     // `fitted_deaths` from the first observed day (`N_days_before+1`) to the
  //     // last death date
  //     fitted_deaths[N_days_before+N_days_av : N_days_before+lastDeathDate],
  //   phi_die
  // ); // optional, but likelie unnecessary: / N_days_av;
  target += neg_binomial_2_lpmf(
    // `obs_cas` from the first observed day to the last death date
    obs_cas_mvs[1:lastCaseWeek] |
      // `fitted_cases` from the first observed day (`N_days_before+1`) to the
      // last death date
      fitted_cases_mvs[N_weeks_before+1 : N_weeks_before+lastCaseWeek],
    phi_cas
  ) ;// Optional, but likely unncessesary: / N_days_av;

// for hospitalizations: use lastCaseWeek as last observation 
// this is still to adjust in the future and add a lastHospiWeek variable
  target += neg_binomial_2_lpmf(
    // `obs_die` from the first observed day to the last death date
    obs_hosp_mvs[5:lastHospWeek] |
      // `fitted_deaths` from the first observed day (`N_days_before+1`) to the
      // last death date
      fitted_hospitalizations_mvs[N_weeks_before+5 : N_weeks_before+lastHospWeek],
    phi_hosp
  ); // optional, but likelie unnecessary: / N_days_av;
}
```


# How the IFR is Used

## Previous Version

In the earlier implementation, those who die is calculated as those who die among the symptomatic and severe: `new_die_dx = dx_sym_die + dx_sev_die;`, where `dx_sym_die` and `dx_sev_die` are informed by `p_die_if_sympt` and `p_die_if_sevt` respectively:

```{stan  output.var="", eval=FALSE}


for(i in 1:N_days_tot){
  p_die_if_sevt[i] = p_die_if_sevt[i] * pow(ifr_vac_adj[i], prob_vac[1]);
  p_sev_if_symt[i] = p_sev_if_sym * pow(ifr_vac_adj[i], prob_vac[2]);
  p_sym_if_inft[i] = p_sym_if_inf * pow(ifr_vac_adj[i], prob_vac[3]);
  }


```


and `dx_sym_die` is calculated as 

```{stan  output.var="", eval=FALSE}
  for(i in 1:N_days_tot) {
    dx_sym_die[i] = dot_product(dx_sym_sev[idx1[i]:i],
      sev_prg_delay_rv[idx2[i]:Max_delay]) * p_die_if_sevt[i];
  }
```

It is then `new_die_dx` that is used, after convolution with the reporting delay (to produce `occur_die`), that is used in the likelihood:

```{stan  output.var="", eval=FALSE}

 target += neg_binomial_2_lpmf(tmp_obs_die | tmp_occur_die, phi_die)/
          N_days_av;


```

where  `neg_binomial_2_lpmf(ints n | reals mu, reals phi)` is the negative binomial probability mass of $n$ given location $\mu$ and precision $\phi$.

## New Version

Here, the likelihood instead considers hospitalizations rather than deaths:

```{stan  output.var="", eval=FALSE}
 target += neg_binomial_2_lpmf(
    // `obs_die` from the first observed day to the last death date
    obs_hosp_mvs[5:lastHospWeek] |
      // `fitted_deaths` from the first observed day (`N_days_before+1`) to the
      // last death date
      fitted_hospitalizations_mvs[N_weeks_before+5 : N_weeks_before+lastHospWeek],
    phi_hosp
  )
```

where `fitted_hospitalizations` is the number of diagnoses among the severe (`_mv` indicates a moving sum), and relies on `p_diag_if_sym`:

```{stan  output.var="", eval=FALSE}
// DIAGNOSIS // 
  // rate ratio of diagnosis at asymptomatic vs symptomatic, symptomatic vs severe
  rr_diag_sym_vs_sev = inv_logit(spl_basis_dx * logit(spl_par_sym_dx));
  p_diag_if_sym = p_diag_if_sev * rr_diag_sym_vs_sev;
  diagnoses_severe = p_diag_if_sev * conv1d(severe - dx_sym_sev, sev_diag_delay_rv);
fitted_hospitalizations = diagnoses_severe;

```


The probability `p_sev_if_symt[i] = p_sev_if_sym  * pow(ifr_vac_adj[i], prob_vac[2]);` is used to calculate the number of severe cases; so the fitted hospitalizations in this sense is related to the IFR since `severe = p_sev_if_symt .*conv1d(symptomatic, sym_prg_delay_rv);` (and diagnoses among the severe is then calculated from this value). The prior for `prob_vac` is the same for both implementations.



# Summary 

* Reinfections are handled differently in that the earlier implementation did not allow reinfections and as such infections were subtracted from the population at each time step, while the newer implementation does allow for reinfections by modeling the protection from immunity to the virus.
* The earlier model used a likelihood on cases and on deaths, while the newer implementation includes a likelihood on cases and hospitalizations.
* Both use the IFR in the estimation of fitted hospitalizations or fitted deaths, since both use the IFR in the calculation of the probabilities of transitioning between states:

```{stan  output.var="", eval=FALSE}
 for( i in 1:N_weeks_tot){
  p_die_if_sevt[i]     = p_die_if_sevt[i]   .* pow(ifr_vac_adj[i], prob_vac[1]);
  p_sev_if_symt[i]     = p_sev_if_sym        * pow(ifr_vac_adj[i], prob_vac[2]);
  p_sym_if_inft[i]     = p_sym_if_inf        * pow(ifr_vac_adj[i], prob_vac[3]);
  }
```


* Newer model is at the weekly time step instead of daily.

